---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-network
  labels:
    provider: azure
    component: network
spec:
  package: xpkg.upbound.io/upbound/provider-azure-network:v1.3.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1